spring:
  application:
    name: membership
  datasource:
    url: jdbc:postgresql://localhost:5432/sideproject
    username: yejinkim
    password: 5352
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
